Set public the access modifier of GivensFGFT::update_L() to fix clang-macOS (suprisingly) specific error of compilation.
The error is due to the function pointer used from GivensFGFTParallel, error log:
Error

        MatDense() : MatGeneric<FPP,Cpu>(), mat(0,0), isIdentity(false), isZeros(false) {}
        ^
/.../faust/wrapper/matlab/src/mexfgftgivensReal.cpp:73:30: note: in instantiation of member function 'Faust::MatDense<double, Device::Cpu>::MatDense' requested here
        Faust::MatDense<SCALAR,Cpu> Lap;
                                    ^
/.../faust/src/faust_linear_operator/CPU/faust_MatDense.hpp:1077:14: note: allocated with 'new[]' here
        FPP *data = new FPP[this->getNbCol()*n];
                    ^
In file included from /.../faust/wrapper/matlab/src/mexfgftgivensReal.cpp:37:
In file included from /.../faust/src/algorithm/factorization/faust_GivensFGFTParallel.h:91:

/.../faust/src/algorithm/factorization/faust_GivensFGFTParallel.hpp:96:33: error: 'update_L' is a protected member of 'Faust::GivensFGFT<double, Device::Cpu, double>'

                &GivensFGFT<FPP,DEVICE,FPP2>::update_L,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/.../faust/src/algorithm/factorization/faust_GivensFGFTParallel.h:86:3: note: in instantiation of member function 'Faust::GivensFGFTParallel<double, Device::Cpu, double>::next_step' requested here
                GivensFGFTParallel(Faust::MatDense<FPP,DEVICE>& Lap, int J, int t, unsigned int verbosity = 0);
                ^
/.../faust/wrapper/matlab/src/mexfgftgivensReal.cpp:89:15: note: in instantiation of member function 'Faust::GivensFGFTParallel<double, Device::Cpu, double>::GivensFGFTParallel' requested here
                        algo = new GivensFGFTParallel<SCALAR,Cpu,FPP2>(Lap, J, t, verbosity);
                                   ^
/.../faust/src/algorithm/factorization/faust_GivensFGFT.h:157:18: note: must name member using the type of the current context 'Faust::GivensFGFTParallel<double, Device::Cpu, double>'
                                virtual void update_L();