update setup.py by being explicit on the minimum numpy version needed to avoid ABI incompatibilities.
Example of error if pyfaust is compiled with numpy 1.20 but used with numpy 1.19:

import pyfaust gives:
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject